config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'projects#index'

  resources 'projects' do
    resource 'pdf_creates', only: [:show]
    resource 'files', only: [:create, :update, :destroy]
    resource 'error_pages', only: [:show]
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects
  end

  def show
    open_file @project.id
    get_pdf_file @project.id
    get_err_file @project.id
    get_sty_files @project.id
    get_tex_files @project.id
    get_image_files @project.id
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end

  def create
    project = current_user.projects.build project_params

    if project.save
      init_directory project.id, params[:template]
      redirect_to project_path(project)
    else
      redirect_to :new
    end
  end

  def update
    if @project.update project_params
      redirect_to :show, project_path(project)
    else
      redirect_to :edit
    end
  end

  def destroy
    @project.delete
    redirect_to projects_path
  end

  private

  def set_project
    @project = current_user.projects.find params[:id]
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def init_directory id, template
    FileUtils.mkdir "#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}"
    FileUtils.copy_entry("#{Rails.root}/public/vtex_data/#{template}/", "#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/")
  end

  def get_pdf_file id
    unless File.exist?("#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/document.pdf")
      @pdf_file = nil
      return
    end

    files = Dir.glob "#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/document.pdf"
    f_name = File.basename(files.first)
    @pdf_file = { name: f_name, path: "/vtex_data/#{current_user.number}/#{id}/#{f_name}" }
  end

  def get_err_file id
    unless File.exist?("#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/errors/error.err")
      @err_file = nil
      return
    end

    files = Dir.glob "#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/errors/error.err"
    f_name = File.basename(files.first)
    @err_file = { name: f_name, path: "/vtex_data/#{current_user.number}/#{id}/errors/#{f_name}" }
  end

  def get_sty_files id
    files = Dir.glob "#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/*.sty"

    @sty_files = []
    files.each do |f|
      f_name = File.basename(f)
      @sty_files << { name: f_name, path: "/vtex_data/#{current_user.number}/#{id}/#{f_name}" }
    end
  end

  def get_tex_files id
    files = Dir.glob("#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/*.tex").sort

    @tex_files = []
    files.each do |f|
      f_name = File.basename(f)
      @tex_files << { name: f_name, path: "/vtex_data/#{current_user.number}/#{id}/#{f_name}" }
    end
  end

  def get_image_files id
    png = "#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/images/*.png"
    jpg = "#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/images/*.jpg"
    files = Dir.glob([png, jpg]).sort

    @image_files = []
    files.each do |f|
      f_name = File.basename(f)
      @image_files << { name: f_name, path: "/vtex_data/#{current_user.number}/#{id}/images/#{f_name}" }
    end
  end

  def open_file id
    if params[:file].present?
      f_name = params[:file]
    else
      f_name = 'document.tex'
    end

    if f_name == 'document.tex'
      unless File.exist?("#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/document.tex")
        File.write("#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/document.tex", "document")
      end
    end

    if f_name == 'error.err'
      f = Pathname("#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/errors/error.err").expand_path.read(encoding: Encoding::UTF_8)
    else
      f = Pathname("#{Rails.root}/public/vtex_data/#{current_user.number}/#{id}/#{f_name}").expand_path.read(encoding: Encoding::UTF_8)
    end

    @open_file = { name: f_name, content: f }
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<h1>プロジェクト一覧</h1>

<%= link_to '新規作成', new_project_path, class: "btn btn-primary" %>

<table class="table">
  <thead>
    <tr>
      <td>プロジェクト名</td>
      <td>説明</td>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project), class: "btn btn-link" %></td>
        <td><%= project.description %></td>
        <td><%= link_to '削除', project_path(project), method: :delete, data: { confirm: '削除しますか?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>プロジェクト作成</h1>

<div class="col-lg-3">
<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label 'プロジェクト名' %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label '説明' %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label 'テンプレート' %>
    <div class="radio">
      <label><%= radio_button_tag :template, 'template_blank' %>空のテンプレート</label>
    </div>
    <div class="radio">
      <label><%= radio_button_tag :template, 'template_soturon', { checked: true } %>卒論</label>
    </div>
    <div class="radio">
      <label><%= radio_button_tag :template, 'template_syuron' %>修論</label>
    </div>
    <div class="radio">
      <label><%= radio_button_tag :template, 'template_ieee' %>IEEE</label>
    </div>
    <div class="radio">
      <label><%= radio_button_tag :template, 'template_group_s' %>伊藤伸一先生グループ</label>
    </div>
  </div>

  <p>
    <%= f.submit '作成', class: "btn btn-primary" %>
  </p>
<% end %>

<p>
  <%= link_to '戻る', projects_path, class: "btn btn-info" %>
</p>
</div>

app/views/projects/show.html.erb
<h1><%= @open_file[:name] %></h1>

<%= form_tag project_files_path(@project, file: @open_file[:name]), remote: true, method: :put, id: 'update' do |f| %>
  <p><%= text_area_tag :content, @open_file[:content], class: "form-control", id: 'file_text_area', style: "min-width: 100%; margin-bottom: 60px" %></p>
  <%= submit_tag '保存', class: "btn btn-primary navbar-btn", id: "update_button", style: "display:none" %>
<% end %>

<div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <div class="col-lg-offset-3 col-lg-4">
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li><button type="button" class="btn btn-primary navbar-btn", id="pdf_update_under">PDF更新</button></li>
        </ul>
      </div>
    </div>
  </div>
</div>